### ISSUE TITLE
 instadefuse and Instaplant

### ISSUE THREAD

**Issue by gRiHoNdAbRo** [B3none/cs2-instadefuse#1]
where should I upload the files?
 problem with instadefuse and Instaplant, what am I doing wrong? thx. 
![изображение_2024-01-12_004046227](https://github.com/B3none/cs2-instadefuse/assets/156356780/7b8e19e5-79dc-4343-a546-f849d8efee8f)

thx

**Comment by B3none** [comment]
Upload them into the plugin directory 👍
