### ISSUE TITLE
translation error in 1.4.0 version

### ISSUE THREAD

**Issue by freakexeuLow** [B3none/cs2-instadefuse#7]
Hey B3none :)

your latest version displays an error: [https://pastebin.com/VgF5SYnR](https://pastebin.com/VgF5SYnR) my Sharp version is 159 and here is a German translation of Instadefuse and thanks for your work 👍🏼 
[de.json](https://github.com/B3none/cs2-instadefuse/files/14075167/de.json)

**Comment by B3none** [comment]
@freakexeuLow can you make a pull request to add the `de.json` into the `lang/` directory.

**Comment by B3none** [comment]
This is fixed in the latest release. Also, don't forget to add your translations 👍
